name: Publish package to npm
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run test
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/index.*
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
      - run: npm --no-git-tag-version version from-git
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
